services:
  - type: web
    name: subliminal-meditation
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Store version info during build
      VERSION_INFO=$(git describe --tags --abbrev=0 2>/dev/null || echo 'dev')-$(git rev-parse --short HEAD)
      BUILD_DATE=$(date -u '+%d.%m.%y %H:%M UTC')
      COMMIT_DATE=$(git show -s --format=%ci HEAD)
      echo "number: $VERSION_INFO" > .version
      echo "sha: $(git rev-parse --short HEAD)" >> .version
      echo "build_date: $BUILD_DATE" >> .version
      echo "commit_date: $COMMIT_DATE" >> .version
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
