# Site Information
site:
  name: "Template App"
  description: "A powerful flask app with authentication and database capabilities"
  tagline: "Transform your development using AI"
  keywords: ["template", "automation", "AI", "coding"]
  theme: "template"

# Company Information
company:
  name: "Exponentials Studio"

# Version Information
version:
  file: "version.txt"
  number: "1.0.0"
  build_date: "2024-01-01"

# Features Configuration
features:
  - name: "Dark Mode"
    icon: "🌙"
    description: "Toggle between light and dark themes"
    enabled: true

  - name: "First Track"
    icon: "🧘‍♂️"
    description: "Manage and track user sessions"
    enabled: true

  - name: "Background Sounds"
    icon: "🎵"
    description: "Mix and customize background sounds"
    enabled: true

  - name: "User Profiles"
    icon: "👤"
    description: "Personalized profile tracking"
    enabled: true

  - name: "Responsive Design"
    icon: "📱"
    description: "Modern UI optimized for all devices"
    enabled: true

  - name: "Firebase Integration"
    icon: "🔐"
    description: "Secure authentication and data storage"
    enabled: true

# Branding
branding:
  themes:
    light:
      primary_color: "#7C4DFF"
      secondary_color: "#B388FF"
      accent_color: "#3F51B5"
      background_color: "#FFFFFF"
      surface_color: "#F5F5F5"
      text:
        primary: "#212121"
        secondary: "#757575"
        accent: "#7C4DFF"
      border_color: "#E0E0E0"
      shadow: "rgba(0, 0, 0, 0.1)"
      success: "#4CAF50"
      warning: "#FFC107"
      error: "#F44336"
      info: "#2196F3"

    dark:
      primary_color: "#B388FF"
      secondary_color: "#7C4DFF"
      accent_color: "#3F51B5"
      background_color: "#121212"
      surface_color: "#1E1E1E"
      text:
        primary: "#FFFFFF"
        secondary: "#B0B0B0"
        accent: "#B388FF"
      border_color: "#333333"
      shadow: "rgba(0, 0, 0, 0.3)"
      success: "#81C784"
      warning: "#FFD54F"
      error: "#E57373"
      info: "#64B5F6"
  
  logo:
    type: "lotus"
    favicon_sizes: [16, 32, 48]
    favicon_formats: ["ico", "png"]
    apple_touch_icon: true
    dark_mode_compatible: true

  avatar:
    default_theme: "meditation"
    default_path: "app/static/img/avatars/default.png"
    dark_mode_path: "app/static/img/avatars/default-dark.png"

# Theme Settings
theme:
  default_mode: "light"  # can be "light", "dark", or "system"
  allow_user_preference: true
  persist_preference: true
  transition_duration: "0.3s"
  auto_switch:
    enabled: true
    start_dark_mode: "18:00"  # 6 PM
    end_dark_mode: "06:00"    # 6 AM

# Content Directories
directories:
  static:
    sounds: "app/static/sounds"
    images: "app/static/img"
    styles: "app/static/css"
    scripts: "app/static/js"

# Default Session Settings
session_defaults:
  duration_minutes: 20
  background_volume: 0.5
  subliminal_volume: 0.3
  auto_start_delay: 5

# Available Meditation Types
meditation_types:
  - name: "Mindfulness"
    description: "Focus on the present moment"
    duration_range: [5, 60]
    
  - name: "Breathing"
    description: "Guided breathing exercises"
    duration_range: [10, 45]
    
  - name: "Body Scan"
    description: "Progressive body awareness"
    duration_range: [15, 45]
    
  - name: "Loving-Kindness"
    description: "Cultivate compassion and love"
    duration_range: [10, 30]

# Background Sounds
background_sounds:
  - name: "Rain"
    file: "rain.mp3"
    category: "Nature"
    
  - name: "Ocean Waves"
    file: "waves.mp3"
    category: "Nature"
    
  - name: "Tibetan Bowls"
    file: "bowls.mp3"
    category: "Instruments"
    
  - name: "White Noise"
    file: "white-noise.mp3"
    category: "Ambient"

# Repository Information
repository:
  username: "wizardsupreme"
  name: "subliminal"
  description: "A powerful meditation app with subliminal messaging capabilities, built with Flask and Firebase"
